### ISSUE TITLE
Support de l'activité du serveur

### ISSUE THREAD

**Issue by Bluzzi** [Virtual-Royaume/Royaume-API#5]
Lorsque le temps de vocal en minute ou un message est ajouté à l'activité d'un utilisateur, l'activité du serveur du jour devrait être incrémenté automatiquement. 

## TODO
- [x] supprimé la requête ``updateServerActivity()``
- [x] créer une requête pour mettre à jour le nombre de membre sur le serveur dans la ``ServerActivity``
- [x] incrémenter la ``ServerActivity`` quand un ``MemberActivity`` est incrémenté
